# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stepper_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(693, 617)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.comboBox_port = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_port.setObjectName("comboBox_port")
        self.horizontalLayout_5.addWidget(self.comboBox_port)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.comboBox_baudrate = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.horizontalLayout_6.addWidget(self.comboBox_baudrate)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_connect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_connect.setCheckable(True)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.horizontalLayout_7.addWidget(self.pushButton_connect)
        self.pushButton_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.horizontalLayout_7.addWidget(self.pushButton_refresh)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.textBrowser_terminal = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_terminal.setObjectName("textBrowser_terminal")
        self.horizontalLayout_3.addWidget(self.textBrowser_terminal)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_direction = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_direction.setObjectName("comboBox_direction")
        self.verticalLayout_2.addWidget(self.comboBox_direction)
        self.lineEdit_degrees = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_degrees.setObjectName("lineEdit_degrees")
        self.verticalLayout_2.addWidget(self.lineEdit_degrees)
        self.lineEdit_pause = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pause.setObjectName("lineEdit_pause")
        self.verticalLayout_2.addWidget(self.lineEdit_pause)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.pushButton_addMove = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_addMove.setObjectName("pushButton_addMove")
        self.verticalLayout_5.addWidget(self.pushButton_addMove)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tableView_sequence = QtWidgets.QTableView(self.centralwidget)
        self.tableView_sequence.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView_sequence.setObjectName("tableView_sequence")
        self.verticalLayout.addWidget(self.tableView_sequence)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_removeLast = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_removeLast.setObjectName("pushButton_removeLast")
        self.horizontalLayout.addWidget(self.pushButton_removeLast)
        self.pushButton_send = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_send.setObjectName("pushButton_send")
        self.horizontalLayout.addWidget(self.pushButton_send)
        self.pushButton_clearAll = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clearAll.setObjectName("pushButton_clearAll")
        self.horizontalLayout.addWidget(self.pushButton_clearAll)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 693, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stepper Control Apingenierios"))
        self.label_3.setText(_translate("MainWindow", "Serial"))
        self.label_8.setText(_translate("MainWindow", "Port"))
        self.label_7.setText(_translate("MainWindow", "Baudrate"))
        self.pushButton_connect.setText(_translate("MainWindow", "CONNECT"))
        self.pushButton_refresh.setText(_translate("MainWindow", "REFRESH"))
        self.label.setText(_translate("MainWindow", "Edit Move"))
        self.label_4.setText(_translate("MainWindow", "Direction"))
        self.label_5.setText(_translate("MainWindow", "Degrees"))
        self.label_6.setText(_translate("MainWindow", "Pause"))
        self.pushButton_addMove.setText(_translate("MainWindow", "ADD MOVE"))
        self.label_2.setText(_translate("MainWindow", "Sequence"))
        self.pushButton_removeLast.setText(_translate("MainWindow", "REMOVE LAST"))
        self.pushButton_send.setText(_translate("MainWindow", "SEND"))
        self.pushButton_clearAll.setText(_translate("MainWindow", "CLEAR ALL"))

