# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'terminal_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 377)
        MainWindow.setStyleSheet("#btn_connect:checked{background-color:rgb(115,210,22);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.textBrowser_terminal = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_terminal.setObjectName("textBrowser_terminal")
        self.verticalLayout_2.addWidget(self.textBrowser_terminal)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_input = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.horizontalLayout_9.addWidget(self.lineEdit_input)
        self.btn_send = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send.setObjectName("btn_send")
        self.horizontalLayout_9.addWidget(self.btn_send)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout_10.addWidget(self.btn_clear)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.combo_port = QtWidgets.QComboBox(self.centralwidget)
        self.combo_port.setObjectName("combo_port")
        self.horizontalLayout.addWidget(self.combo_port)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.combo_baud = QtWidgets.QComboBox(self.centralwidget)
        self.combo_baud.setObjectName("combo_baud")
        self.horizontalLayout_2.addWidget(self.combo_baud)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.combo_databits = QtWidgets.QComboBox(self.centralwidget)
        self.combo_databits.setObjectName("combo_databits")
        self.horizontalLayout_3.addWidget(self.combo_databits)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.combo_parity = QtWidgets.QComboBox(self.centralwidget)
        self.combo_parity.setObjectName("combo_parity")
        self.horizontalLayout_4.addWidget(self.combo_parity)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.combo_stopbits = QtWidgets.QComboBox(self.centralwidget)
        self.combo_stopbits.setObjectName("combo_stopbits")
        self.horizontalLayout_5.addWidget(self.combo_stopbits)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.combo_flow = QtWidgets.QComboBox(self.centralwidget)
        self.combo_flow.setObjectName("combo_flow")
        self.horizontalLayout_6.addWidget(self.combo_flow)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.check_echo = QtWidgets.QCheckBox(self.centralwidget)
        self.check_echo.setObjectName("check_echo")
        self.verticalLayout.addWidget(self.check_echo)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_connect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_connect.setStyleSheet("")
        self.btn_connect.setCheckable(True)
        self.btn_connect.setObjectName("btn_connect")
        self.horizontalLayout_7.addWidget(self.btn_connect)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.btn_refresh.setObjectName("btn_refresh")
        self.horizontalLayout_8.addWidget(self.btn_refresh)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 621, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TheApp Title"))
        self.label.setText(_translate("MainWindow", "Serial Communication"))
        self.btn_send.setText(_translate("MainWindow", "SEND"))
        self.btn_clear.setText(_translate("MainWindow", "CLEAR TERMINAL"))
        self.label_2.setText(_translate("MainWindow", "Settings"))
        self.label_10.setText(_translate("MainWindow", "Port"))
        self.label_3.setText(_translate("MainWindow", "Baud Rate"))
        self.label_4.setText(_translate("MainWindow", "Data Bits"))
        self.label_5.setText(_translate("MainWindow", "Parity"))
        self.label_6.setText(_translate("MainWindow", "Stop Bits"))
        self.label_7.setText(_translate("MainWindow", "Flow Control"))
        self.check_echo.setText(_translate("MainWindow", "Local Echo"))
        self.btn_connect.setText(_translate("MainWindow", "CONNECT"))
        self.btn_refresh.setText(_translate("MainWindow", "REFRESH"))

