#include "MCG.h"

void MCG_Init(void) {  
  //MCGC2 = 0x36;
  MCGC2 = (~MCGC2_BDIV_MASK & MCGC2_RANGE_MASK | MCGC2_HGO_MASK | MCGC2_EREFS_MASK | MCGC2_ERCLKEN_MASK);
  while(!MCGSC_OSCINIT);
  //MCGC1 = 0xB8;
  MCGC1 = (MCGC1_CLKS1_MASK & ~MCGC1_CLKS0_MASK | MCGC1_RDIV_MASK & ~MCGC1_IREFS_MASK);
  while(MCGSC_IREFST);
  while(MCGSC_CLKST != 2);
  MCGC2_LP = 1;
  //MCGC1 = 0x98;
  MCGC1 = (MCGC1_CLKS1_MASK & ~MCGC1_CLKS0_MASK & ~MCGC1_RDIV2_MASK | MCGC1_RDIV1_MASK | MCGC1_RDIV0_MASK & ~MCGC1_IREFS_MASK);
  MCGC3 = (MCGC3_PLLS_MASK | MCGC3_VDIV2_MASK);
  while(!MCGSC_PLLST);
  MCGC2_LP = 0;
  while(!MCGSC_LOCK);
  //MCGC1 = 0x18;
  MCGC1 = (MCGC1_RDIV1_MASK | MCGC1_RDIV0_MASK & ~MCGC1_IREFS_MASK);
  while(MCGSC_CLKST != 3);
}